# Autogenerated wrapper script for Makemsix_jll for armv7l-linux-gnueabihf
export libmsix, makemsix

using Zlib_jll
using Xerces_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("Makemsix")
JLLWrappers.@declare_library_product(libmsix, "libmsix.so")
JLLWrappers.@declare_executable_product(makemsix)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Xerces_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libmsix,
        "lib/libmsix.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        makemsix,
        "bin/makemsix",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
